interface ItemPrices {
    [key: string]: number;
}

const mappedData: ItemPrices = {
    "Anarkali": 0,
    'Blazer': 1,
    'Blouse': 2,
    'Capri': 3,
    'Chinos': 4,
    'Denim Jacket': 5,
    'Denim Shorts': 6,
    'Dhoti': 7,
    'Dress': 8,
    'Gown': 9,
    'Hoodie': 10,
    'Jacket': 11,
    'Jeans': 12,
    'Joggers': 13,
    'Jumpsuit': 14,
    'Kurta': 15,
    'Kurta Set': 16,
    'Kurti': 17,
    'Lehenga': 18,
    'Maxi Dress': 19,
    'Palazzo': 20,
    'Palazzo Pants': 21,
    'Salwar Kameez': 22,
    'Salwar Suit': 23,
    'Saree': 24,
    'Sari': 25,
    'Shawl': 26,
    'Sherwani': 27,
    'Shirt': 28,
    'Shorts': 29,
    'Skirt': 30,
    'Suit': 31,
    'Sweater': 32,
    'Sweatpants': 33,
    'Sweatshirt': 34,
    'T-Shirt': 35,
    'Tank Top': 36,
    'Tie': 37,
    'Top': 38,
    'Track Pants': 39,
    'Trouser': 41,
    'Tuxedo': 42,
    '28': 0,
    '30': 1,
    '32': 2,
    '34': 3,
    '36': 4,
    'F': 5,
    'L': 6,
    'M': 7,
    'S': 8,
    'XL': 9,
    'XS': 10,
    'Beige': 0,
    'Black': 1,
    'Blue': 2,
    'Brown': 3,
    'Cream': 4,
    'Green': 5,
    'Grey': 6,
    'Khaki': 7,
    'Maroon': 8,
    'Navy Blue': 9,
    'Orange': 10,
    'Pink': 11,
    'Purple': 12,
    'Red': 13,
    'White': 14,
    'Yellow': 15,
    'Cashmere': 0,
    'Chiffon': 1,
    'Chino': 2,
    'Cotton': 3,
    'Crepe': 4,
    'Denim': 5,
    'Fleece': 6,
    'Georgette': 7,
    'Jersey': 8,
    'Lace': 9,
    'Leather': 10,
    'Linen': 11,
    'Net': 12,
    'Polyester': 13,
    'Raw Silk': 14,
    'Rayon': 15,
    'Satin': 16,
    'Silk': 17,
    'Twill': 18,
    'Velvet': 19,
    'Wool': 20,
    'Abu Jani Sandeep Khosla': 0,
    'Adidas': 1,
    'Adrianna Papell': 2,
    'Allen Solly': 3,
    'Anita Dongre': 4,
    'Armani': 5,
    'Arrow': 6,
    'BIBA': 7,
    'Biba': 8,
    'Blackberrys': 9,
    'Bombay Selections': 10,
    'Brooks Brothers': 11,
    'Calvin Klein': 12,
    'Champion': 13,
    "David's Bridal": 14,
    'Dolce & Gabbana': 15,
    'Ermenegildo Zegna': 16,
    'FabIndia': 17,
    'Forever 21': 18,
    'Forever New': 19,
    'Gap': 20,
    'Global Desi': 21,
    'Gucci': 22,
    'H&M': 23,
    'Hugo Boss': 24,
    'Lacoste': 25, 
    'Lakshya': 26,
    'Lee': 27,
    "Levi's": 28,
    'Levis': 29,
    'Libas': 30,
    'Louis Philippe': 31,
    'Mango': 32,
    'Manish Malhotra': 33,
    'Manyavar': 34,
    'Meena Bazaar': 35,
    'Michael Kors': 36,
    'Neeta Lulla': 37,
    'Nike': 38,
    'Only': 39,
    'Pantaloons': 40,
    'Park Avenue': 41,
    'Pepe Jeans': 42,
    'Peter England': 43,
    'Polo Ralph Lauren': 44,
    'Puma': 45,
    'Ralph Lauren': 46,
    'Rangriti': 47,
    'Raw Mango': 48,
    'Raymond': 49,
    'Reebok': 50,
    'Ritu Kumar': 51,
    'Rohit Bal': 52,
    'Sabhyata': 53,
    'Sabyasachi': 54,
    'Satya Paul': 55,
    'Siyaram': 56,
    'Tarun Tahiliani': 57,
    'Tommy Hilfiger': 58,
    'Under Armour': 59,
    'United Colors of Benetton': 60,
    'Van Heusen': 61,
    'Versace': 62,
    'W': 63,
    'W for Women': 64,
    'Westside': 65,
    'Wrangler': 66,
    'Zara': 67,
    'Zimmermann': 68,
    'No': 0,
    'Yes': 1,
    "Ahmedabad": 0,
    "Bangalore": 1,
    "Bhopal": 2,
    "Chandigarh": 3,
    "Chennai": 4,
    "Delhi": 5,
    "Hyderabad": 6,
    "Jaipur": 7,
    "Kolkata": 8,
    "Lucknow": 9,
    "Mumbai": 10,
    "Pune": 11,
    "Fair": 0,
    "Good": 1,
    "Like New": 2,
    "New": 3,
    "Refurbished": 4,
    "Used": 5,
    "Casual": 0,
    "Festive": 1,
    "Form": 2,
    "Formal": 3,
    "Outdoor": 4,
    "Party": 5,
    "Traditional": 6,
    "Wedding": 7,
}

export default mappedData
																																															
